In [59]:
import pandas as pd
import numpy as np

In [61]:
rank = pd.read_csv("/Users/yaseminerdemli/Documents/BA Courses/Dissertation/Project/Data/ranknet_v5.csv")
rank

,index,State,ZipCode,state_abbreviation,USPS_ZIP_PREF_CITY,Higher Education,% Unemployment,"% Business, Science, Arts",% Poverty,Median Income,...,PC5,PC6,PC7,PC8,PC9,PC10,Cluster,Cluster_Grouped,TierLabel,RankNetScore
0,2236,New York,10022,NY,New York,0.830930,0.025207,0.742029,0.050798,250001.0,...,-1.817704,-2.896836,-16.783327,-1.053338,-15.718966,25.835216,6,1,1st Tier,173.762240
1,2234,New York,10019,NY,New York,0.736736,0.051556,0.725343,0.118789,182763.0,...,-4.411639,2.487980,-1.471451,-1.192995,-6.480255,7.710162,6,1,1st Tier,137.562240
2,2232,New York,10017,NY,New York,0.852226,0.046157,0.777277,0.070912,201667.0,...,-0.352900,-3.117835,-14.447444,-1.722555,-11.676077,14.066206,6,1,1st Tier,123.053810
3,2242,New York,10028,NY,New York,0.819728,0.038573,0.770777,0.052641,236888.0,...,-5.740641,-6.546480,-0.702688,-2.472539,19.024892,-8.263569,6,1,1st Tier,102.709110
4,2222,New York,10005,NY,New York,0.916692,0.022960,0.756653,0.075369,250001.0,...,-3.536114,-9.991512,-9.156508,-1.844852,12.933289,-0.187371,6,1,1st Tier,100.240400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,7063,North Carolina,27607,NC,Raleigh,0.721320,0.027648,0.623518,0.110618,140238.0,...,-2.527490,4.197045,6.319100,1.791279,-1.184787,0.443657,9,1,1st Tier,32.218670
296,2492,New York,11374,NY,Rego Park,0.544298,0.034866,0.535466,0.114201,96378.0,...,-1.644912,-2.334900,-2.615512,-0.299270,3.098696,-1.293241,0,1,1st Tier,32.217945
297,26386,California,92866,CA,Orange,0.344838,0.026629,0.364682,0.180201,91462.0,...,-3.734930,4.040088,-2.025134,1.508728,-0.641653,-1.336825,8,1,1st Tier,32.171734
298,26079,California,91754,CA,Monterey Park,0.367525,0.053627,0.419436,0.111572,76152.0,...,-2.788638,1.842686,-0.019538,0.512017,-1.102171,-0.253662,8,1,1st Tier,32.166820
299,5272,Virginia,20147,VA,Ashburn,0.657327,0.032376,0.630698,0.043267,162588.0,...,0.088169,3.817740,5.184715,0.599044,2.776836,-0.578261,9,1,1st Tier,32.111588

In [63]:
rank = rank.sort_values('RankNetScore', ascending=False)
rank['rank_index'] = range(len(rank))
rank['rank_index'] = rank['rank_index'] + 1

In [65]:
ahp = pd.read_csv("/Users/yaseminerdemli/Documents/BA Courses/Dissertation/Project/Data/ahp_300_v1.csv")
ahp

,State,ZipCode,state_abbreviation,USPS_ZIP_PREF_CITY,land_area,population,people per sq mile,Basic Education,Higher Education,% Income < 40k,...,Competititors,HighIncomeDensity,PotentialResidents_euclid,HighIncomeDensity_euclid,Average Daily Traffic Counts_euclid,EmployeeNumber_euclid,Median Household Income_euclid,near_city_center_euclid,Competititors_euclid,TotalScore
0,New York,10022,NY,New York,0.443409,31574.0,71207.398440,0.145235,0.830930,0.060831,...,2.0,14788.309563,0.023254,0.121135,0.001812,0.393909,0.013360,0.021921,0.124035,0.113284
1,New York,10028,NY,New York,0.316574,47962.0,151503.265600,0.158707,0.819728,0.034738,...,2.0,28764.419569,0.036054,0.235616,0.004649,0.015676,0.010901,0.021921,0.124035,0.087500
2,New York,10019,NY,New York,0.658885,45521.0,69087.937500,0.226928,0.736736,0.141406,...,3.0,13706.608860,0.032943,0.112274,0.001562,0.204591,0.009201,0.021921,0.186052,0.086881
3,New York,10005,NY,New York,0.072868,8664.0,118900.093800,0.080770,0.916692,0.018254,...,1.0,26843.050044,0.008698,0.219878,0.000860,0.078780,0.016816,0.021921,0.062017,0.080859
4,New York,10023,NY,New York,0.969282,62228.0,64200.097660,0.150785,0.830165,0.075933,...,1.0,25013.166213,0.045946,0.204889,0.000966,0.022709,0.011755,0.021921,0.062017,0.080283
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,California,94588,CA,Pleasanton,32.739845,36324.0,1109.473755,0.312907,0.658997,0.069929,...,0.0,232.419668,0.024140,0.001904,0.047456,0.019097,0.013601,0.021921,0.000000,0.015709
296,New York,11220,NY,Brooklyn,1.727934,90657.0,52465.539060,0.345889,0.231863,0.392105,...,0.0,3312.567677,0.013737,0.027134,0.002588,0.019295,0.004449,0.000000,0.000000,0.015647
297,California,92780,CA,Tustin,6.274362,58654.0,9348.202148,0.487426,0.353927,0.209181,...,0.0,1007.397070,0.017316,0.008252,0.066403,0.022719,0.006682,0.021921,0.000000,0.015629
298,Texas,76244,TX,Keller,14.906641,78815.0,5287.240723,0.484727,0.478917,0.078099,...,0.0,752.183387,0.033572,0.006161,0.003391,0.002188,0.009324,0.021921,0.000000,0.015619
299,New York,11234,NY,Brooklyn,7.384077,90372.0,12238.767580,0.525911,0.361517,0.174783,...,0.0,1198.203023,0.030605,0.009815,0.003087,0.009848,0.007606,0.000000,0.000000,0.015614

In [67]:
rank.columns

Index(['index', 'State', 'ZipCode', 'state_abbreviation', 'USPS_ZIP_PREF_CITY',
       'Higher Education', '% Unemployment', '% Business, Science, Arts',
       '% Poverty', 'Median Income', 'numberofStarbucks',
       'Average Daily Traffic Counts', 'Total Traffic Counts',
       'Count of Transit Stops', 'EmployeeNumber', 'near_city_center',
       'PotentialResidents', 'Competititors', 'HighIncomeDensity', 'PC1',
       'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8', 'PC9', 'PC10',
       'Cluster', 'Cluster_Grouped', 'TierLabel', 'RankNetScore',
       'rank_index'],
      dtype='object')

In [69]:
rank = rank.drop(columns=['index','PC1','PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8', 'PC9', 'PC10'])

In [71]:
ahp = ahp[['State', 'ZipCode', 'state_abbreviation', 'USPS_ZIP_PREF_CITY',
       'Higher Education', '% Unemployment', '% Business, Science, Arts',
       '% Poverty', 'Median Income', 'numberofStarbucks',
       'Average Daily Traffic Counts', 'Total Traffic Counts',
       'Count of Transit Stops', 'EmployeeNumber', 'near_city_center',
       'PotentialResidents', 'Competititors', 'HighIncomeDensity','TotalScore']]

In [73]:
ahp = ahp.sort_values('TotalScore', ascending=False)
ahp['ahp_index'] = range(len(ahp))
ahp['ahp_index'] = ahp['ahp_index'] + 1

In [75]:
rank['rank']=1

In [77]:
ahp['ahp']=1

In [79]:
final = pd.merge(rank,
                 ahp, 
                 on = ['State', 'ZipCode', 'state_abbreviation', 'USPS_ZIP_PREF_CITY'],
                how = 'outer')

In [81]:
final.columns

Index(['State', 'ZipCode', 'state_abbreviation', 'USPS_ZIP_PREF_CITY',
       'Higher Education_x', '% Unemployment_x', '% Business, Science, Arts_x',
       '% Poverty_x', 'Median Income_x', 'numberofStarbucks_x',
       'Average Daily Traffic Counts_x', 'Total Traffic Counts_x',
       'Count of Transit Stops_x', 'EmployeeNumber_x', 'near_city_center_x',
       'PotentialResidents_x', 'Competititors_x', 'HighIncomeDensity_x',
       'Cluster', 'Cluster_Grouped', 'TierLabel', 'RankNetScore', 'rank_index',
       'rank', 'Higher Education_y', '% Unemployment_y',
       '% Business, Science, Arts_y', '% Poverty_y', 'Median Income_y',
       'numberofStarbucks_y', 'Average Daily Traffic Counts_y',
       'Total Traffic Counts_y', 'Count of Transit Stops_y',
       'EmployeeNumber_y', 'near_city_center_y', 'PotentialResidents_y',
       'Competititors_y', 'HighIncomeDensity_y', 'TotalScore', 'ahp_index',
       'ahp'],
      dtype='object')

In [83]:
import re

# find all the base names that have both an _x and an _y
cols = final.columns
bases = {
    re.sub(r'_[xy]$','',c)
    for c in cols
    if re.search(r'_[xy]$', c)
}

for base in bases:
    xcol = base + '_x'
    ycol = base + '_y'
    if xcol in cols and ycol in cols:
        final[base] = final[xcol].combine_first(final[ycol])
        final.drop([xcol, ycol], axis=1, inplace=True)

In [85]:
import numpy as np

# Option A: nested np.where
final['common'] = np.where(
    (final['ahp'] == 1) & (final['rank'] == 1),      # both are 1
    'both',
    np.where(
        final['rank'] == 1,                         # else: rank is 1
        'rank',
        'ahp'                                       # else: ahp must be 1
    )
)

In [87]:
final[final['common'] == 'both']

,State,ZipCode,state_abbreviation,USPS_ZIP_PREF_CITY,Cluster,Cluster_Grouped,TierLabel,RankNetScore,rank_index,rank,...,Average Daily Traffic Counts,near_city_center,% Poverty,PotentialResidents,HighIncomeDensity,% Unemployment,Total Traffic Counts,Competititors,Count of Transit Stops,common
0,Arizona,85016,AZ,Phoenix,0.0,1.0,1st Tier,38.161606,137.0,1.0,...,167569.00000,0.0,0.127025,8724.008183,606.823303,0.034598,167569.0,0.0,123.0,both
1,Arizona,85254,AZ,Scottsdale,0.0,1.0,1st Tier,32.506344,285.0,1.0,...,27905.87500,0.0,0.049569,13708.152364,596.702191,0.028945,223247.0,0.0,102.0,both
3,Arizona,85260,AZ,Scottsdale,9.0,1.0,1st Tier,38.015705,142.0,1.0,...,26943.85742,0.0,0.055415,12103.503774,495.464809,0.034049,188607.0,1.0,78.0,both
10,California,90017,CA,Los Angeles,8.0,1.0,1st Tier,43.846317,69.0,1.0,...,282333.34380,1.0,0.373032,2389.939381,3701.586434,0.053489,847000.0,0.0,116.0,both
12,California,90024,CA,Los Angeles,9.0,1.0,1st Tier,37.322395,150.0,1.0,...,12182.50000,1.0,0.296240,22052.090204,3275.365412,0.094046,97460.0,1.0,95.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420,Washington,98103,WA,Seattle,0.0,1.0,1st Tier,36.697166,157.0,1.0,...,21645.11719,1.0,0.074176,26960.834029,1575.582237,0.028483,735934.0,0.0,332.0,both
422,Washington,98105,WA,Seattle,0.0,1.0,1st Tier,43.548702,72.0,1.0,...,25987.66016,1.0,0.260279,28434.198177,1195.455535,0.055720,1221420.0,0.0,392.0,both
423,Washington,98109,WA,Seattle,0.0,1.0,1st Tier,39.231420,119.0,1.0,...,19564.00000,1.0,0.078832,18141.589452,2121.303006,0.040519,215204.0,0.0,243.0,both
424,Washington,98115,WA,Seattle,0.0,1.0,1st Tier,38.546740,129.0,1.0,...,35801.02344,1.0,0.071958,26758.204630,1002.548710,0.035669,1646847.0,0.0,456.0,both
425,Washington,98121,WA,Seattle,0.0,1.0,1st Tier,36.260147,170.0,1.0,...,17886.42773,1.0,0.074736,13108.120854,6019.206742,0.036033,125205.0,0.0,62.0,both

In [89]:
final.columns

Index(['State', 'ZipCode', 'state_abbreviation', 'USPS_ZIP_PREF_CITY',
       'Cluster', 'Cluster_Grouped', 'TierLabel', 'RankNetScore', 'rank_index',
       'rank', 'TotalScore', 'ahp_index', 'ahp', 'numberofStarbucks',
       '% Business, Science, Arts', 'Higher Education', 'Median Income',
       'EmployeeNumber', 'Average Daily Traffic Counts', 'near_city_center',
       '% Poverty', 'PotentialResidents', 'HighIncomeDensity',
       '% Unemployment', 'Total Traffic Counts', 'Competititors',
       'Count of Transit Stops', 'common'],
      dtype='object')

In [53]:
final.to_csv("/Users/yaseminerdemli/Documents/BA Courses/Dissertation/Project/Data/comparison.csv",index = False)